---
# Source: generic-backend-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mock-service-v1-secret
type: Opaque
data: {}
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-service-v1-config-map
data:
    JAVA_OPTS: "-Xms256M -Xmx256M"
    MOCK_PORT: "8082"
---
# Source: generic-backend-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mock-service-v1
  labels:
    app: mock-service-v1
spec:
  type: NodePort
  selector:
    app: mock-service-v1
  ipFamilies:
    - IPv4
  ports:
    - name: mock-service-v1
      port: 8082
      nodePort: 30082
---
# Source: generic-backend-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service-v1
  labels:
    app: mock-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-service-v1
  template:
    metadata:
      labels:
        app: mock-service-v1
    spec:
      containers:
        - name: mock-service-v1
          image: "miguelarmasabt/mock-service:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30

          env:
              - name: JAVA_OPTS
                valueFrom:
                  configMapKeyRef:
                    name: mock-service-v1-config-map
                    key: JAVA_OPTS

              - name: MOCK_PORT
                valueFrom:
                  configMapKeyRef:
                    name: mock-service-v1-config-map
                    key: MOCK_PORT